version: "3.8"
networks:
  asset-cost-averaging-network:
    external: false
services:
  asset-cost-averaging:
    image: ghcr.io/atz3n/kraken-invest/asset-cost-averaging:latest
    # To use the locally built image, comment the line above and uncomment the line below
    # image: asset-cost-averaging
    networks:
      - asset-cost-averaging-network
    environment: 
      # Minimum required configuration.
      # Check the settings.env file for the full set of configuration variables
      - KRAKEN_API_KEY=<your Kraken API key>
      - KRAKEN_PRIVATE_KEY=<your Kraken private key>
      - BASE_SYMBOL=XXBT
      - QUOTE_SYMBOL=ZEUR
      - QUOTE_INVESTING_AMOUNT=100