name: build asset cost average image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - asset-cost-average/**

env:
  # github config
  PROJECT_DIR: asset-cost-average
  
  # docker config
  IMAGE_NAME: asset-cost-average
  IMAGE_TAG: latest
  REGISTRY_NAME: ghcr.io/atz3n/kraken-invest

jobs:
  test-project:
    uses: ./.github/workflows/test-asset-cost-average.yml
    secrets: inherit

  build-image:
    runs-on: ubuntu-latest
    needs:
      - test-project
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.PROJECT_DIR }}/docker/Dockerfile
          context: ./${{ env.PROJECT_DIR }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}