name: build asset-cost-averaging image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Docker image version tag
        required: false

  push:
    branches:
      - main
    paths:
      - asset-cost-averaging/**

env:
  # github config
  PROJECT_DIR: asset-cost-averaging
  
  # docker config
  IMAGE_NAME: asset-cost-averaging
  REGISTRY_NAME: ghcr.io/atz3n/kraken-invest
  DEFAULT_IMAGE_TAG: latest

jobs:
  test-project:
    uses: ./.github/workflows/test-asset-cost-averaging.yml
    secrets: inherit

  build-image:
    runs-on: ubuntu-latest
    needs:
      - test-project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set image tag
        run: |
          if [ "${{ github.event.inputs.version }}" == "" ]; then
            echo "IMAGE_TAG=${{ env.DEFAULT_IMAGE_TAG }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: ./${{ env.PROJECT_DIR }}/docker/Dockerfile
          context: ./${{ env.PROJECT_DIR }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}