name: deploy asset-cost-averaging image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Docker image version tag
        required: false

jobs:
  test-asset-cost-averaging:
    uses: ./.github/workflows/zz_test-project.yml
    secrets: inherit
    with:
      project_dir: packages/asset-cost-averaging

  deploy-asset-cost-averaging:
    needs:
      - test-asset-cost-averaging
    uses: ./.github/workflows/zz_deploy-image.yml
    secrets: inherit
    with:
      project_dir: packages/asset-cost-averaging
      registry_name: ghcr.io/atz3n/crypto-invest
      image_name: asset-cost-averaging
      version: ${{ github.event.inputs.version }}