name: deploy market-cap-weighting image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Docker image version tag
        required: false

jobs:
  test-market-cap-weighting:
    uses: ./.github/workflows/zz_test-project.yml
    secrets: inherit
    with:
      project_dir: packages/market-cap-weighting

  deploy-market-cap-weighting:
    needs:
      - test-market-cap-weighting
    uses: ./.github/workflows/zz_deploy-image.yml
    secrets: inherit
    with:
      project_dir: packages/market-cap-weighting
      registry_name: ghcr.io/atz3n/crypto-invest
      image_name: market-cap-weighting
      version: ${{ github.event.inputs.version }}