name: test lib project

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - packages/lib/**

jobs:
  test-lib:
    uses: ./.github/workflows/lib/test-project.yml
    secrets: inherit
    with:
      project_dir: packages/lib