name: test asset-cost-averaging project

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - packages/asset-cost-averaging/**

jobs:
  test-asset-cost-averaging:
    uses: ./.github/workflows/zz_test-project.yml
    secrets: inherit
    with:
      project_dir: packages/asset-cost-averaging